version: "3.7"

services: 
    app:
        restart: always
        build: .
        links: 
            - mongo
        ports: 
            - "3000"  
        volumes: 
            - .:/usr/src/app
        environment:
            - MONGO_URL=mongodb://mongo/jumpers-drivers-selector
    mongo:
        image: mongo
        ports: 
            - "27017"
