version: "3.7"

services: 
    app:
        build: .
        restart: always
        depends_on: 
            - mongo
        volumes:
            - .:/usr/src/app
        environment:
            - MONGO_URL=mongodb://mongo:27017/jumpers-drivers-selector
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/storage/keys/client_credentials.json
        networks:
            - app_network
        ports:
            - "3000:3000"
    mongo:
        image: mongo:4.4
        networks:
            - app_network
        ports: 
            - "27017:27017"
networks: 
    app_network:
